<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GhopoCadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'NO' => 1,
                'Jarak' => 3.2,
                'latitude' => -6.88402,
                'longitude' => 111.9278,
                'No_ID' => 456000, // Assuming this should be an integer
                'Komoditi' => "Cad Batugamping",
                'Lokasi_IUP' => "IUP Temandang",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' => 180290209,
                'Catatan' => "Luas 752,8 Hektar. Produksi 16,236,480 ton/tahun.",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "RKAB Tahun 2022, PT Semen Indonesia (Persero) Tbk Kuari Batugamping Temandang",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Merakurak, Kerek",
                'Luas_ha' => 752.8,
                'Masa_Berlaku_IUP' => Carbon::create(2029, 5, 14),
                'Masa_Berlaku_PPKH' => Carbon::create(2029, 5, 14),
            ],
            [
                'NO' => 2,
                'Jarak' => 11.6,
                'latitude' => -6.892200,
                'longitude' => 111.954580,
                'No_ID' => 456100, // Assuming this should be an integer
                'Komoditi' => "Cad Batugamping",
                'Lokasi_IUP' => "IUP Tuwiri",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' => 160602000,
                'Catatan' => "CaO 46% - 54%, MgO < 2%, Luas 458,9 Hektar.",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "RKAB Tahun 2022, PT Semen Indonesia (Persero) Tbk Kuari Batugamping Tuwiri",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Merakurak, Kerek",
                'Luas_ha' => 458.9,
                'Masa_Berlaku_IUP' => Carbon::create(2032, 3, 27),
                'Masa_Berlaku_PPKH' => Carbon::create(2032, 3, 27),
            ],
            [
                'NO' => 3,
                'Jarak' => 2.8,
                'latitude' => -6.850910,
                'longitude' => 111.936740,
                'No_ID' => 456200, // Assuming this should be an integer
                'Komoditi' => "Cad Lempung",
                'Lokasi_IUP' => "IUP Tlogowaru",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' => 4982366,
                'Catatan' => "Al2O3 6%-17%, Luas 120,04 Hektar, Rencana Produksi 1,217,736 ton/tahun.",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "RKAB Tahun 2022, PT Semen Indonesia (Persero) Tbk Kuari Clay Tlogowaru",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Merakurak, Kerek",
                'Luas_ha' => 120.04,
                'Masa_Berlaku_IUP' => Carbon::create(2033, 8, 6),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'NO' => 4,
                'Jarak' => 10.4,
                'latitude' => -6.83144,
                'longitude' => 111.90826,
                'No_ID' => null,
                'Komoditi' => "Cad Lempung",
                'Lokasi_IUP' => "IUP Mliwang",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' => 1789302,
                'Catatan' => null,
                'Status_Penyelidikan' => null,
                'Acuan' => null,
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Kerek",
                'Luas_ha' => 201.6,
                'Masa_Berlaku_IUP' => Carbon::create(2022, 12, 31),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'NO' => 5,
                'Jarak' => 6.6,
                'latitude' => -6.83671,
                'longitude' => 111.89629,
                'No_ID' => null,
                'Komoditi' => "Cad Lempung",
                'Lokasi_IUP' => "IUP Tobo",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' => 748651,
                'Catatan' => null,
                'Status_Penyelidikan' => null,
                'Acuan' => null,
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Merakurak",
                'Luas_ha' => 5,
                'Masa_Berlaku_IUP' => Carbon::create(2024, 11, 15),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'NO' => 6,
                'Jarak' => 5.7,
                'latitude' => -6.82047,
                'longitude' => 111.91368,
                'No_ID' => null,
                'Komoditi' => "Cad Lempung",
                'Lokasi_IUP' => "IUP Karangasem",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' => 2893654,
                'Catatan' => null,
                'Status_Penyelidikan' => null,
                'Acuan' => null,
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Jenu",
                'Luas_ha' => 35.75,
                'Masa_Berlaku_IUP' => Carbon::create(2024, 11, 15),
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'NO' => 7,
                'Jarak' => 8.7,
                'latitude' => -6.89834,
                'longitude' => 111.92986,
                'No_ID' => 252700, // Assuming this should be an integer
                'Komoditi' => "Pot Batugamping",
                'Lokasi_IUP' => "Merakurak",
                'Tipe_SD_Cadangan' => "SD Tertunjuk",
                'SD_Cadangan_ton' => 89642000,
                'Catatan' => "CaO rata-rata : 51,54%",
                'Status_Penyelidikan' => "Eksplorasi Rinci",
                'Acuan' => "652/Ga/88",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Kerek",
                'Luas_ha' => null,
                'Masa_Berlaku_IUP' => null,
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'NO' => 8,
                'Jarak' => 9.3,
                'latitude' => -6.90992,
                'longitude' => 111.87768,
                'No_ID' => 252600, // Fixed to numeric value
                'Komoditi' => "Pot Batugamping",
                'Lokasi_IUP' => "Kerek",
                'Tipe_SD_Cadangan' => "SD Tertunjuk",
                'SD_Cadangan_ton' => 535773000,
                'Catatan' => "Baik",
                'Status_Penyelidikan' => "Eksplorasi Rinci",
                'Acuan' => "Neraca",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Kerek",
                'Luas_ha' => null,
                'Masa_Berlaku_IUP' => null,
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'NO' => 9,
                'Jarak' => 11.1,
                'latitude' => -6.89220,
                'longitude' => 111.96557,
                'No_ID' => 362400, // Fixed to numeric value
                'Komoditi' => "Pot Batugamping",
                'Lokasi_IUP' => "Tiwiri Kulon",
                'Tipe_SD_Cadangan' => "Cadangan Terkira",
                'SD_Cadangan_ton' => 912576,
                'Catatan' => "IUP Aktif",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "Sdr, Khusni Mubaroch, RKAB 2017",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Merakurak",
                'Luas_ha' => null,
                'Masa_Berlaku_IUP' => null,
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'NO' => 10,
                'Jarak' => 14,
                'latitude' => -6.90243,
                'longitude' => 112.01226,
                'No_ID' => 252900, // Fixed to numeric value
                'Komoditi' => "Pot Batugamping",
                'Lokasi_IUP' => "Sugiharjo",
                'Tipe_SD_Cadangan' => "SD Terukur",
                'SD_Cadangan_ton' => 300000000,
                'Catatan' => "Komposisi kimia : CaO= 4,48 - 55,3%",
                'Status_Penyelidikan' => "Studi Kelayakan",
                'Acuan' => "Neraca",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Tuban",
                'Luas_ha' => null,
                'Masa_Berlaku_IUP' => null,
                'Masa_Berlaku_PPKH' => null,
            ],
            [
                'NO' => 11,
                'Jarak' => 32.8,
                'latitude' => -6.93651,
                'longitude' => 112.15508,
                'No_ID' => 419000, // Fixed to numeric value
                'Komoditi' => "Pot Batugamping",
                'Lokasi_IUP' => "Leranwetan",
                'Tipe_SD_Cadangan' => "Cadangan Terbukti",
                'SD_Cadangan_ton' =>  529673,
                'Catatan' => "IUP 2018, Luas 1,32 Ha",
                'Status_Penyelidikan' => "Operasi Produksi",
                'Acuan' => "RKAB 2021, a,n Yusuf Wibisono",
                'Kabupaten' => "Tuban",
                'Kecamatan' => "Palang",
                'Luas_ha' => 1.32,
                'Masa_Berlaku_IUP' => null,
                'Masa_Berlaku_PPKH' => null,
            ],
            // Additional entries can be added here following the same structure
        ];

        DB::table('ghopo_cad_bb')->insert($data);
    }
}
